# Generated by Django 5.2.1 on 2025-06-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_API', '0003_newuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
